[project]
name = "cp-libs"
version = "0.1.0"
description = "競技プログラミング用(python)"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.2",
    "online-judge-tools>=11.5.1",
    "online-judge-verify-helper>=5.6.0",
    "pulp>=2.9.0",
    "setuptools>=75.6.0",
]
