name: verify

on:
  push:
    branches:
      - main
    paths:
      - 'library-verify-problems/**'
      - 'cps/**'
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install dependencies
      run: pip3 install -U online-judge-verify-helper

    - name: Set up Rust (1.70.0)
      uses: dtolnay/rust-toolchain@1.70.0

    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        cd ./library-verify-problems
        oj-verify run
